<?php

/**
 * Implements hook_requirements().
 */
// function dkan_datastore_requirements($phase) {
//   $requirements = [];

//   // Ensure that common module is enabled before enabling dkan_common.
//   if ($phase == 'install') {
//     if (!\Drupal::moduleHandler()->moduleExists('datastore')) {
//       $requirements['dkan_datastore'] = [
//         'title' => t('Datastore module is not enabled'),
//         'description' => t('The "datastore" module must be enabled before installing dkan_datastore.'),
//         'severity' => REQUIREMENT_ERROR,
//       ];
//     }
//   }

//   return $requirements;
// }
