<?php

/**
 * @file
 * Install, update and uninstall functions for the metastore_search module.
 */

/**
 * Implements hook_install().
 */
function metastore_search_install() {
  // If fresh 2.23 install: Run the update hook to enable the transitional module.
  metastore_search_update_9001();
}

/**
 * Enable transitional dkan_metastore_search transition module, in preparation for 4.x.
 */
function metastore_search_update_9001() {
  if (!\Drupal::moduleHandler()->moduleExists('dkan_metastore_search')) {
    \Drupal::service('module_installer')->install(['dkan_metastore_search']);
  }

}
