<?php

/**
 * @file
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\datastore\DataNodeLifeCycle;
use Drupal\common\Exception\DataNodeLifeCycleEntityValidationException;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function datastore_node_insert(EntityInterface $entity) {
  try {
    (new DataNodeLifeCycle($entity))->insert();
  }
  catch (DataNodeLifeCycleEntityValidationException $e) {
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete().
 */
function datastore_node_predelete(EntityInterface $entity) {
  try {
    (new DataNodeLifeCycle($entity))->predelete();
  }
  catch (DataNodeLifeCycleEntityValidationException $e) {
  }
}
