<?php

/**
 * @file
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\common\Exception\DataNodeLifeCycleEntityValidationException;
use Drupal\common\Resource;
use Drupal\metastore\LifeCycle\Data as LifeCycle;
use Drupal\metastore\NodeWrapper\Data;

/**
 * Implements hook_node_load().
 */
function metastore_node_load(array $entities) {

  foreach ($entities as $entity) {
    try {
      metastore_get_data_node_lifecycle($entity)->load();
    }
    catch (DataNodeLifeCycleEntityValidationException $e) {
    }
  }
}

/**
 * Implements hook_entity_presave().
 */
function metastore_entity_presave(EntityInterface $entity) {
  try {
    metastore_get_data_node_lifecycle($entity)->presave();
  }
  catch (DataNodeLifeCycleEntityValidationException $e) {
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete().
 */
function metastore_node_predelete(EntityInterface $entity) {
  try {
    metastore_get_data_node_lifecycle($entity)->predelete();
  }
  catch (DataNodeLifeCycleEntityValidationException $e) {
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function metastore_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($bundle === 'data') {
    if (isset($fields['field_json_metadata'])) {
      $fields['field_json_metadata']->addConstraint('ProperJson', []);
    }
  }
}

/**
 * Helper method to retrieve the static value for a resource's display.
 */
function resource_mapper_display() {
  return drupal_static('metastore_resource_mapper_display', Resource::DEFAULT_SOURCE_PERSPECTIVE);
}

/**
 * Helper method to retrieve the static value for a resource's revisioning.
 */
function resource_mapper_new_revision() {
  return drupal_static('metastore_resource_mapper_new_revision', 0);
}

/**
 * Create a LifeCycle object.
 */
function metastore_get_data_node_lifecycle($entity) {
  $data = new Data($entity);

  $lifeCycle = new LifeCycle($data);
  $lifeCycle->setFileMapper(\Drupal::service('dkan.metastore.resource_mapper'));

  return $lifeCycle;
}
