<?php

/**
 * @file
 * DKAN Datastore - Fast Import.
 */

use Dkan\Datastore\Manager\Info;

/**
 * Implements hook_xautoload().
 */
function dkan_datastore_fast_import_xautoload($adapter) {
  $adapter->absolute()->addPsr4(
    'Dkan\Datastore\Manager\FastImport\\',
    drupal_get_path("module", "dkan_datastore_fast_import") . '/src'
  );
}

/**
 * Implements hook_dkan_datastore_manager().
 */
function dkan_datastore_fast_import_dkan_datastore_manager() {
  $info = new Info(
    '\Dkan\Datastore\Manager\FastImport\FastImport',
    "fast",
    "Fast Import",
    "MYSQL"
  );

  return $info;
}
