<?php

/**
 * @file
 * Install, update and uninstall functions for the dkan_common module.
 */

/**
 * Implements hook_install().
 */
function dkan_common_install() {
  // If old common module is installed, copy setting
  // always_use_existing_local_perspective.
  if (\Drupal::moduleHandler()->moduleExists('common')) {
    $config = \Drupal::configFactory()->getEditable('common.settings');
    $local_perspective = $config->get('always_use_existing_local_perspective');
    \Drupal::configFactory()->getEditable('dkan_common.settings')
      ->set('always_use_existing_local_perspective', $local_perspective)
      ->save();
    \Drupal::logger('dkan_common')->notice('Copied config from common.');
  }

}
