<?php

/**
 * @file
 * Install file for the datastore_mysql_import module.
 */

/**
 * Implements hook_install().
 */
function datastore_mysql_import_install() {
  // Set the schema version to ensure update hooks run properly.
  \Drupal::service('update.update_hook_registry')->setInstalledVersion('datastore_mysql_import', 10001);

  // Only in DKAN 3.x: Run the update hooks to enable transitional modules.
  datastore_mysql_import_update_10002();
}

/**
 * Update hook to set new setting strict_mode_disabled to TRUE.
 */
function datastore_mysql_import_update_10001(&$sandbox) {
  \Drupal::configFactory()->getEditable('datastore_mysql_import.settings')
    ->set('strict_mode_disabled', TRUE)
    ->save();
  // Add a message to indicate the update was successful.
  \Drupal::messenger()->addStatus(t('Strict mode for MySQL table creation is now optional via the setting @setting. It has now been set to TRUE for consistency with previous behavior. To keep strict mode enabled for imports uncheck "Disable innodb_strict_mode for imports" at /admin/dkan/datastore/mysql_import/.',
  [
    '@setting' => 'strict_mode_disabled',
  ]));
}

/**
 * Enable transitional module dkan_datastore_mysql_import.
 */
function datastore_mysql_import_update_10002() {
  if (!\Drupal::moduleHandler()->moduleExists('dkan_datastore_mysql_import')) {
    \Drupal::service('module_installer')->install(['dkan_datastore_mysql_import']);
  }
}
