<?php

/**
 * @file
 * Data API via services.
 */

// TODO: Add search element, investigate caching, add uuids.

/**
 * Implements hook_ctools_plugin_api().
 */
function dkan_data_api_ctools_plugin_api($owner, $api) {
  if ($owner == 'services' && $api == 'services') {
    return array(
      'version' => 3,
    );
  }
}

/**
 * Implements hook_services_resources.
 */
function dkan_data_api_services_resources() {
  return array(
    'dkan_datastore_search' => array(
      'index' => array(
        'file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/user_resource'),
        'description' => 'Data API for DKAN datastores',
        'callback' => '_dkan_data_api_datastore_index',
        'args' => array(
          array(
            'name' => 'resource_id',
            'optional' => FALSE,
            'type' => 'array',
            'description' => 'id or alias of the resource to be searched against.',
            'default value' => 0,
            'source' => array('param' => 'resource_id'),
          ),
          array(
            'name' => 'filters',
            'optional' => TRUE,
            'type' => 'string',
            'description' => 'matching conditions to select.',
            'default value' => 0,
            'source' => array('param' => 'filters'),
          ),
          array(
            'name' => 'query',
            'optional' => TRUE,
            'type' => 'string',
            'description' => 'matching conditions to select.',
            'default value' => 0,
            'source' => array('param' => 'query'),
          ),
          array(
            'name' => 'language',
            'optional' => TRUE,
            'type' => 'string',
            'description' => 'language of the full text query (default: en)',
            'default value' => 'en',
            'source' => array('param' => 'language'),
          ),
          array(
            'name' => 'offset',
            'optional' => TRUE,
            'type' => 'int',
            'description' => 'offset this number of rows',
            'default value' => 0,
            'source' => array('param' => 'offset'),
          ),
          array(
            'name' => 'limit',
            'optional' => TRUE,
            'type' => 'int',
            'description' => 'maximum number of rows to return (default: 100).',
            'default value' => variable_get('dkan_data_api_index_limit', 100),
            'source' => array('param' => 'limit'),
          ),
          array(
            'name' => 'fields',
            'optional' => TRUE,
            'type' => array(),
            'description' => 'fields to return as a list or comma separated string (default: all fields in original order).',
            'default value' => '*',
            'source' => array('param' => 'fields'),
          ),
          array(
            'name' => 'sort',
            'optional' => TRUE,
            'type' => 'string',
            'description' => 'comma separated field names with ordering e.g.: “fieldname1, fieldname2 desc.',
            'default value' => '',
            'source' => array('param' => 'sort'),
          ),
          array(
            'name' => 'join',
            'optional' => TRUE,
            'type' => 'array',
            'description' => 'array of values to join on if including multiple datasets.',
            'default value' => '',
            'source' => array('param' => 'join'),
          ),
        ),
        'access callback' => '_dkan_data_api_datastore_access',
        'access arguments' => array('view'),
        'access arguments append' => FALSE,
      ),
    ),
  );
}

/**
 * Creates index based off of query.
 * For arguments, see: dkan_data_api_services_resources().
 */
function _dkan_data_api_datastore_index($resource_ids, $filters, $query, $language, $offset, $limit, $fields, $sort, $join) {
  try {
    // Query for a single resource.
    if (count($resource_ids) < 2) {
      $resource_id = array_shift(array_values($resource_ids));
      $table = dkan_data_api_tablename($resource_id);
      $data_select = dkan_data_api_build_index_query($table, $offset, $limit, $fields, $sort);
      dkan_data_api_add_index_conditions($data_select, $filters);
    }
    else {
      // Query for a multiple resources.
      $i = 0;
      foreach ($resource_ids as $alias => $resource_id) {
        // We can't have multiple resources if we can't join them.
        if (!$join) {
          throw new Exception('Mulitple resources require joins.');
        }
        $table = dkan_data_api_tablename($resource_id);
        // For the first resource we are creating the base query.
        if ($i == 0) {
          $fields = isset($fields[$alias]) ? $fields[$alias] : $fields;
          $sort = isset($sort[$alias]) ? $sort[$alias] : $sort;
          $filters = isset($filters[$alias]) ? $filters[$alias] : $filters;
          $data_select = dkan_data_api_build_index_query($table, $offset, $limit, $fields, $sort, $alias);
          dkan_data_api_add_index_conditions($data_select, $filters, $alias);
        }
        // For the additional resources we are adding joins, fields, filters.
        else {
          $newfields = isset($fields[$alias]) ? $fields[$alias] : '*';
          $sort = isset($sort[$alias]) ? $sort[$alias] : '';
          $filters = isset($filters[$alias]) ? $filters[$alias] : '';

          dkan_data_api_build_additional_index_query($data_select, $table, $fields, $sort, $alias, $join);
          if ($filters) {
            dkan_data_api_add_index_conditions($data_select, $filters, $alias);
          }
        }
        $i++;
      }
    }
  }
  catch(Exception $ex) {
    return array( 'Caught exception: ' . $ex->getMessage());
  }
  $results = services_resource_execute_index_query($data_select);
  return dkan_data_api_resource_build_index_list($results, $table, $fields);

  return $output;
}

/**
 * Adds conditions, ie WHERE clause, to query.
 */
function dkan_data_api_add_index_conditions(&$data_select, $filters, $alias = 't') {
  if (is_array($filters)) {
    foreach($filters as $num => $filter) {
      if (is_array($filter)) {
        foreach($filter as $key => $value) {
          $data_select->condition($num . '.' . $key, $filter, 'IN');
        }
      }
      else {
        $data_select->condition($alias . '.' . $num, services_str_getcsv($filter), 'IN');
      }
    }
  }
}

/**
 * Adds additional fields and join.
 */
function dkan_data_api_build_additional_index_query(&$data_select, $table, $fields, $sort, $alias, $join) {
  $aliases = array_keys($join);
  $joint = $aliases[0] . '.' . $join[$aliases[0]] . ' = ' . $aliases[1] . '.' . $join[$aliases[1]];
  $data_select->addJoin('INNER', $table, $alias, $joint);

  // AddField doesn't work with asterisk after join.
  if ($fields == '*') {
    $schema = drupal_get_schema($table);
    foreach ($schema['fields'] as $name => $element) {
      $data_select->addField($alias, $name);
    }
  }
  else {
    $data_select->addField($alias, explode(',', $fields));
  }
}

/**
 * Returns table name or exeption.
 */
function dkan_data_api_tablename($resource_id) {
  $nid = db_query('SELECT nid FROM {node} WHERE uuid = :uuid', array(':uuid' => $resource_id))->fetchField();
  $table = 'dkan_datastore_' . $nid;
  if (db_table_exists($table)) {
    return $table;
  }
  else {
    throw new Exception('Resource ' . $resource_id . ' does not exist.');
  }
}

/**
 * Builds index query.
 */
function dkan_data_api_build_index_query($table, $offset, $limit, $fields, $sort, $alias = 't') {
  $data_select = db_select($table, $alias);
  if (isset($sort) && is_array($sort)) {
    foreach($sort as $field => $type) {
      $data_select->orderBy($alias . ' .' . $field, $type);
    }
  }
  else {
    $data_select->orderBy($alias . '.timestamp', 'DESC');
  }
  dkan_data_api_resource_build_index_query($data_select, $offset, $fields, $limit, $alias, $table);
  return $data_select;
}

/**
 * Same as services version but not adding conditions.
 */
function dkan_data_api_resource_build_index_query(&$query, $page, $fields, $page_size, $alias, $table) {
  $default_limit = variable_get("{$table}_index_page_size", 20);
  if (!user_access('perform unlimited index queries') && $page_size > $default_limit) {
    $page_size = $default_limit;
  }
  $query->range($page * $page_size, $page_size);
  if ($fields == '*') {
    $query->fields($alias);
  }
  else {
    $query->fields($alias, explode(',', $fields));
  }
}

/**
 * Access callback.
 */
function _dkan_data_api_datastore_access($op) {
  return TRUE;
}

/**
 * Builds index link with results of the query.
 */
function dkan_data_api_resource_build_index_list($results, $table, $fields) {
  // Put together array of matching items to return.
  $items = array();
  $endpoint_name = services_get_server_info('endpoint');
  $endpoint = services_endpoint_load($endpoint_name);
  GLOBAL $base_url;
  $path = $base_url . '/' . $endpoint->path . '/read/' . $table;
  foreach ($results as $result) {
    $result->uri = $path;
    $items[] = $result;
  }

  $help = array('help' => dkan_data_api_resource_help());
  $count = array('count' => count($items));
  $success = count($items) ? array('success' => true) : array('success' => false);
  $schema = drupal_get_schema($table);
  if ($fields == '*') {
    $fields = array('fields' => $schema['fields']);
  }
  else {
    $used_fields = explode(',', $fields);
    foreach ($used_fields as $key => $field) {
      $output_fields[$field] = $schema['fields'][$field];
    }
    $fields = array('fields' => $output_fields);
  }

  return $help + $success + $count + $fields + array('records' => $items);

  return $items;
}

function dkan_data_api_resource_help() {
  return t('Search a datastore table. :param resource_id: id or alias of the data that is going to be selected.');
}
