version: 2
plugins:
  phpcodesniffer:
    enabled: true
    channel: beta
    config:
      standard: "Drupal,DrupalPractice"
    checks:
      Drupal Commenting Deprecated IncorrectTextLayout:
        enabled: false
      Drupal Commenting Deprecated DeprecatedMissingSeeTag:
        enabled: false
      Drupal Semantics FunctionTriggerError TriggerErrorTextLayoutRelaxed:
        enabled: false
      Drupal Commenting Deprecated DeprecatedWrongSeeUrlFormat:
        enabled: false

exclude_patterns:
  - "cypress/"
  - "config/"
  - "db/"
  - "dist/"
  - "docs/"
  - "documentation/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.yml"
  - "**/*.json"
  - "**/*.js"
  - "**/*.jsx"
  - "*.md"
  - "**/*.md"
  - "*.install"
  - "*.profile"
  - "*.module"
  - "*.xml"
  - "**/*.xml"
  - "**/*.install"
  - "**/*.profile"
  - "**/*.module"
  - ".circleci/"
  - ".gitignore"
