steps:
  - name: Site Setup
    plugin: Drupal
    makeFile: 'build-dkan.make'
    profileName: 'dkan'
    runInstall: true
  - name: Fix Files Folder Permissions
    command: 'chmod -R 777 /var/www/html/sites/default/files && drush cc all'
