image: proboci/ubuntu-16.04-lamp:php-7.2
steps:
  - name: Setup QA site
    plugin: Script
    script: |
      echo "Move code to dkan directory"
      cd ~
      mkdir dkan
      cp -a $SRC_DIR/. ~/dkan/

      apt-get update -y
      
      echo "Install DKAN Tools"
      cd $SRC_DIR
      git clone  https://github.com/GetDKAN/dkan-tools.git
      ln -s $SRC_DIR/dkan-tools/bin/dktl /usr/local/bin/dktl
      chmod +x /usr/local/bin/dktl
      
      export DKTL_MODE="HOST"
      
      echo "Create database"
      mysql -u root -pstrongpassword -e 'create database dkan;'
      
      echo "Initialize project directory"
      cd $SRC_DIR
      dktl init
      cp -a ~/dkan/. $SRC_DIR/dkan/
      
      echo "Run make"
      dktl make
      ln -s $SRC_DIR/docroot /var/www/html
      chmod -R 777 /var/www/html/sites/default/files

      chmod +w docroot/sites/default/settings.php
      printf "// Docker Database Settings\n\$databases['default']['default'] = array(\n  'database' => 'dkan',\n  'username' => 'root',\n  'password' => 'strongpassword',\n  'host' => 'localhost',\n  'port' => '',\n  'driver' => 'mysql',\n  'prefix' => '',\n);\n" >> docroot/sites/default/settings.php
      chmod -w docroot/sites/default/settings.php
      
      echo "Run install" 
      dktl drush site-install dkan --site-name='DKAN' --db-url=mysql://root:strongpassword@127.0.0.1/dkan
      chown -R www-data:www-data /var/www/html/sites/default/files
      dktl deploy test
      dktl drush user-password admin --password="admin"
      dktl test:qa-users
