steps:
  - name: Setup QA site
    # Currently this "Script" is not documented in probo's docs, but it fixes the issue of
    # Probo reporting back immediately that probo is completely ready when it's not. Note that
    # we need to use 'script:' instead of 'command:'
    plugin: Script
    script: |
      # Fail right away.
      set -e
      # Start in the right folder of our checkout (/src)
      cd $SRC_DIR

      echo ""
      echo "Build $BUILD_ID "
      echo ""

      echo ""
      echo "-------> Update drush to latest"
      echo ""
      old_drush=$(which drush)
      composer global require --prefer-source --no-interaction drush/drush:8.0.1
      export PATH="$HOME/.composer/vendor/bin:$PATH"
      rm $old_drush
      which drush
      drush_version=$(drush --version)
      if [ drush_version !== "8.0.1" ]; then
        echo "Drush version is not up to date: $drush_version should be 8.0.1"
        exit 1
      fi

      echo ""
      echo "-------> Install ahoy"
      echo ""
      wget -q https://github.com/devinci-code/ahoy/releases/download/1.1.0/ahoy-`uname -s`-amd64 -O /usr/local/bin/ahoy; chmod +x /usr/local/bin/ahoy

      echo ""
      echo "-------> Run 'bash dkan-init.sh':"
      echo ""
      # Create the proper folder structure
      time bash dkan-init.sh dkan
      #Set a symlink so that probo can serve the site.

      echo ""
      echo "-------> Run 'ahoy dkan drupal-rebuild':"
      echo ""
      # Setup and install DKAN - use 127.0.0.1 instead of localhost
      time ahoy dkan drupal-rebuild mysql://root:strongpassword@127.0.0.1/dkan
      ln -s $SRC_DIR/docroot /var/www/html
      chmod -R 777 /var/www/html/sites/default/files

      echo ""
      echo "-------> Run 'ahoy dkan remake':"
      echo ""
      time ahoy dkan remake

      echo ""
      echo "-------> Run 'ahoy dkan reinstall':"
      echo ""
      time ahoy dkan reinstall

      echo ""
      echo "The url of this build should be at:"
      echo " https://$BUILD_ID.probo.build"
      echo ""
      echo "Known Issues (1/22/2016):"
      echo " - Site may give a SQL error on initial load. Give it a few seconds and then refresh and it should work. This is due to the container apache waking up before the MYSQL. Probo.ci knows, but they say it's not at the top of the priority since few are having that issue."
      echo " - You should usually choose: the Build Permalink (blue button) for doing site QA. If you don't any new commits may blow away the site while you are viewing it as well as the data. 'View Site' Green button shows the latest build, so it can change while you are interacting with it."
      echo ""
