<?php

/**
 * @file
 */

use Drupal\dkan\Util\JobStoreUtil;

/**
 * Implements hook_requirements().
 */
function dkan_requirements($phase): array {
  $requirements = [];
  if ($phase == 'runtime') {
    // Check if the common module is enabled.
    if (\Drupal::moduleHandler()->moduleExists('common')) {
      $requirements['dkan common disabled'] = [
        'title' => t('DKAN Common Module'),
        'value' => t('Enabled'),
        'description' => t('The common module is is deprecated and must be disabled.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
    
    // List all the jobstore tables.
    if ($connection = \Drupal::database()) {
      $job_store_util = new JobStoreUtil(
        $connection,
        \Drupal::service('event_dispatcher')
      );
      if ($tables = $job_store_util->getUnknownJobstoreTables()) {
        $requirements['dkan unknown jobstore tables'] = [
          'title' => t('DKAN Unknown Jobstore Tables'),
          'value' => implode(', ', array_values($tables)),
          'description' => t(
            'This site\'s database has these unknown jobstore tables, which are probably not needed.'
          ),
          'severity' => REQUIREMENT_INFO,
        ];
      }

      // Check for duplicate deprecated/non-deprecated tables.
      if ($duplicates = $job_store_util->getDuplicateJobstoreTables()) {
        $duplicates_message = [];
        foreach ($duplicates as $legacy => $hashed) {
          $duplicates_message[] = $legacy . ' > ' . $hashed;
        }
        $requirements['dkan duplicate deprecated tables'] = [
          'title' => t('DKAN Duplicate Jobstore Tables'),
          'value' => implode(', ', $duplicates_message),
          'description' => t('These jobstore tables are duplicates.  Use drush dkan:jobstore-fixer to reconcile them.'),
          'severity' => REQUIREMENT_ERROR,
        ];
      }

      // Is this site using deprecated table names?
      if ($deprecated_table_names = $job_store_util->getAllDeprecatedJobstoreTableNames()) {
        $requirements['dkan deprecated jobstore tables'] = [
          'title' => t('DKAN Deprecated Jobstore Tables'),
          'value' => implode(', ', $deprecated_table_names),
          'description' => t('Deprecated jobstore tables currently in use. Use drush dkan:jobstore-fixer to rename them.'),
          'severity' => REQUIREMENT_WARNING,
        ];
      }
    }
    // Alert the user if they have always_use_existing_local_perspective on.
    if ($config = \Drupal::config('dkan.settings')) {
      if ($config->get('always_use_existing_local_perspective') ?? FALSE) {
        $requirements['dkan using local files'] = [
          'title' => t('DKAN Using Local Files'),
          'value' => 'always_use_existing_local_perspective: true',
          'description' => t(
            'DKAN is configured to use localized files rather than download them during import.
            Disable this setting on the CLI by running: <code>drush config:set dkan.settings always_use_existing_local_perspective 0</code>'
          ),
          'severity' => REQUIREMENT_WARNING,
        ];
      }
    }
  }
  return $requirements;
}


/**
 * Enable core path and config modules if they are not already.
 */
function dkan_update_9001() {
  $modules = ['path', 'config'];
  \Drupal::service('module_installer')->install($modules);
}

/**
 * Enable data dictionary widget.
 */
function dkan_update_9002() {
  \Drupal::service('module_installer')->install(['data_dictionary_widget']);
}
