<?php
/**
 * @file
 * Code for the NuCivic Data Dashboard feature.
 */

include_once 'dkan_sitewide_profile_page.features.inc';


/**
 * Implements hook_block_info().
 */
function dkan_sitewide_profile_page_block_info() {
  $blocks = array();
  $blocks['dkan_user_summary'] = array(
    'info' => t('DKAN User Summary'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dkan_sitewide_profile_page_block_view($delta = '') {
  global $user;
  $block = array();
  $query = new EntityFieldQuery();

  switch($delta) {
    case 'dkan_user_summary':
      //If is anonymous return empty array.
      if (user_is_anonymous()) {
        return array();
      }
      $account = _gravatar_load_account($user);
      $path = _gravatar_get_account_user_picture($account) ? _gravatar_get_account_user_picture($account) : gravatar_get_gravatar($user->mail);
      $profile_picture = theme_image(
        array(
          'path' => $path,
          'width' => 60,
          'height' => 60,
          'attributes' => array(),
        )
      );
      $menu_data = menu_tree_all_data('menu-command-center-menu', NULL, 2);

      $menu_data = dkan_sitewide_profile_page_remove_profile_menu_item($menu_data);
      $menu_data = dkan_sitewide_profile_page_check_access_visualization($menu_data);
      $menu_data = menu_tree_output($menu_data);
      $menu = drupal_render($menu_data);

      $html = theme('dkan_sitewide_profile_page_dashboard_user_summary', array(
          'num_groups' => dkan_sitewide_profile_page_count_by_type('group'),
          'num_dataset' => dkan_sitewide_profile_page_count_by_type('dataset'),
          'name' => $user->name,
          'since' => format_date($user->created, 'custom', 'm/d/Y'),
          'profile_picture' => $profile_picture,
          'menu' => $menu,
        )
      );
      $block['subject'] = '';
      $block['content'] =  array(
        '#markup' => $html,
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'dkan_sitewide_profile_page') . '/css/dkan_sitewide_profile_page.css',
          ),
          'js' => array(
            drupal_get_path('module', 'dkan_sitewide_profile_page') . '/js/dkan_sitewide_profile_page.js',
          ),
        ),
      );

      break;
  }
  return $block;
}

/**
 * Check if visualizations links are valid or not (Enable module visualization)
 */
function dkan_sitewide_profile_page_check_access_visualization($menu_data) {
  foreach ($menu_data as $key => $menu_item) {
    if ($menu_item['link']['link_path'] == 'admin/structure/entity-type/visualization') {
      if (module_exists('visualization_entity')) {
        //Check childrens
        foreach ($menu_item['below'] as $key_below => $children) {
          if (!module_exists('visualization_entity')) {
            unset($menu_data[$key]['below'][$key_below]);
          }
          elseif (!module_exists('visualization_entity_choropleth_bundle') && ($children['link']['link_path'] == 'admin/structure/entity-type/visualization/choropleth_visualization/add' || $children['link']['link_path'] == 'admin/structure/entity-type/visualization/choropleth_visualization')) {
            unset($menu_data[$key]['below'][$key_below]);
          }
          elseif (!drupal_valid_path($children['link']['link_path'])) {
            unset($menu_data[$key]['below'][$key_below]);
          }
        }
      }
      else {
        unset($menu_data[$key]);
      }
    }
  }

  return $menu_data;
}

function dkan_sitewide_profile_page_remove_profile_menu_item($menu_data){
  foreach ($menu_data as $key => $menu_item) {
    if(isset($menu_item['link']['link_path']) && $menu_item['link']['link_path'] === 'user'){
      unset($menu_data[$key]);
    };
  }
  return $menu_data;
}

/*
 * Get number of nodes created by user
 * of a particular content type.
 */
function dkan_sitewide_profile_page_count_by_type($type){
  global $user;

  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', $type)
  ->propertyCondition('uid', $user->uid)
  ->count();

  return $query->execute();
}

/*
 * Implementation of hook_theme().
 */
function dkan_sitewide_profile_page_theme() {
  return array(
    'dkan_sitewide_profile_page_dashboard_user_summary' => array(
      'arguments' => array(),
      'template' => 'dkan_sitewide_profile_page_dashboard_user_summary',
      'path' => drupal_get_path('module', 'dkan_sitewide_profile_page'),
    )
  );
}
