version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: ubuntu-2004:current
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: Install shunit
          command: |
            cd tests
            wget https://github.com/kward/shunit2/archive/v2.1.8.tar.gz
            mkdir shunit2 && tar xf v2.1.8.tar.gz -C shunit2 --strip-components 1

      - run:
          name: Run tests
          command: |
            export PATH=$PATH:/home/circleci/project/bin
            cd tests
            ./dktl_test.sh

