<?php

/**
 * @file
 * Install, update and uninstall functions for the DKAN dkan_metastore_admin module.
 */

/**
 * Implements hook_install().
 */
function dkan_metastore_admin_install() {
  // If the old metastore_admin module is still enabled, copy config and uninstall it.
  if (\Drupal::moduleHandler()->moduleExists('metastore_admin')) {
    \Drupal::service('module_installer')->uninstall(['metastore_admin']);
    $message = t('The legacy metastore_admin module has been uninstalled.');
  }
  return $message;  
}