<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_presave().
 *
 * Make sure summary and image are populated.
 */
function dkan_data_entity_presave(EntityInterface $entity) {

  if ($entity->bundle() != "data") {
    return;
  }

  $entityType = $entity->getEntityTypeId();

  $metadata = json_decode($entity->get('field_json_metadata')->value);

  $title = isset($metadata->title) ? $metadata->title : $metadata->name;
  if ($entityType == 'node') {
    $entity->setTitle($title);
    $created = new DateTime();
    $created->setTimestamp($entity->getCreatedTime());
    $metadata->created = $created->format('Y-m-d\TH:i:s');

    $changed = new DateTime();
    $changed->setTimestamp($entity->getChangedTime());
    $metadata->modified = $changed->format('Y-m-d\TH:i:s');
  }

  // If there is no uuid add one.
  if (!isset($metadata->identifier)) {
    $metadata->identifier = $entity->uuid();
  }
  // If one exists in the uui it should be the same in the table.
  else {
    $entity->set('uuid', $metadata->identifier);
  }

  $entity->set('field_json_metadata', json_encode($metadata));
}
