<?php

/**
 * @file
 */

/**
 * Uninstall obsolete submodule harvest_dashboard.
 */
function harvest_update_8001(&$sandbox) {
  \Drupal::service('module_installer')->uninstall(['harvest_dashboard']);
}

/**
 * Remove tables if they exist: harvest_source, harvest_run, harvest_hash.
 */
function harvest_update_8002(&$sandbox) {
  foreach (['harvest_source', 'harvest_run', 'harvest_hash'] as $table) {
    \Drupal::database()->schema()->dropTable($table);
  }
}
