<?php

/**
 * @file
 * Install, update and uninstall functions for the dkan_metastore module.
 */

/**
 * Implements hook_install().
 */
function dkan_metastore_install() {
  // If old metastore module is installed, copy all metastore settings.
  if (\Drupal::moduleHandler()->moduleExists('metastore')) {
    $config = \Drupal::configFactory()->getEditable('metastore.settings');
    $settings = $config->getRawData();
    $new_config = \Drupal::configFactory()->getEditable('dkan_metastore.settings');
    foreach ($settings as $key => $value) {
      $new_config->set($key, $value);
    }
    $new_config->save();
    \Drupal::logger('dkan_metastore')->notice('Copied config from metastore.');
  }

}
