<?php

/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_permission().
 */
function dkan_sitewide_menu_permission() {
  return array(
    'administer DKAN configuration' => array(
      'title' => t('Administer DKAN configuration'),
      'description' => t('Perform administration tasks for DKAN.'),
    ),
  );
}

/**
 * Implements hook_menu_alter().
 *
 * Allow site managers access to colorizer form.
 */
function dkan_sitewide_menu_menu_alter(&$items) {
  $items['admin/appearance/colorizer']['access arguments'] = array('administer DKAN configuration');
  $items['admin/config/services/odsm/validate/dcat']['access arguments'] = array('administer DKAN configuration');
}
