# Cypress.io requirements
# https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies

ARG BASE_IMAGE
FROM $BASE_IMAGE

# Given that ddev has installed python3-pip, we can grab yq.
RUN pip3 install yq
