<?php

/**
 * @file
 * Code for the DKAN Data Dictionary tableschema module.
 */

use Dkan\DataDictionary\TableSchemaDataDictionary;

/**
 * Implements hook_xautoload().
 */
function dkan_data_dictionary_tableschema_xautoload($adapter) {
  $adapter->absolute()->addPsr4(
    'Dkan\DataDictionary\\',
    drupal_get_path("module", "dkan_data_dictionary_tableschema") . '/src'
  );
}

/**
 * Implements hook_dkan_data_dictionaries().
 */
function dkan_data_dictionary_tableschema_dkan_data_dictionaries() {
  $dataDictionary = new TableSchemaDataDictionary(
    'dkan_data_dictionary_tableschema_validation',
    'TableSchema',
    array('json'),
    'Dkan\DataDictionary\TableSchemaDataDictionaryManager'
  );

  return array('dkan_data_dictionary_tableschema_validation' => $dataDictionary);
}
