name: User Story
description: User stories are short descriptions of a feature told from the perspective of the person who desires the new functionality, usually a user of the system.
labels: [user story]

body:
  - type: textarea
    attributes:
     label: User Story
     description: As a [user], I want [goal] so that [some reason].
     render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: Set up the scenario. Given [x] When [y] Then [z].
      render: markdown
    validations:
     required: true
