datastore.settings:
  type: config_object
  label: 'Datastore Settings'
  mapping:
    rows_limit:
      type: integer
    purge_file:
      type: boolean
    purge_table:
      type: boolean
    triggering_properties:
      type: sequence
      sequence:
        type: string
    delete_local_resource:
      type: boolean
