datastore.settings:
  type: config_object
  label: 'Datastore Settings'
  mapping:
    rows_limit:
      type: integer
      label: 'Rows limit'
    purge_file:
      type: integer
      label: 'Purge File'
    purge_table:
      type: integer
      label: 'Purge Table'
    triggering_properties:
      type: sequence
      label: 'Triggering Properties'
