<?php

/**
 * @file
 * Install, update and uninstall functions for the DKAN Sample Content module.
 */

/**
 * Implements hook_install().
 */
function sample_content_install() {
  sample_content_update_10001();
}

/**
 * Enable transitional dkan_sample_content module, in preparation for 4.x.
 */
function sample_content_update_10001() {
  if (!\Drupal::service('module_handler')->moduleExists('dkan_sample_content')) {
    \Drupal::service('module_installer')->install(['dkan_sample_content'], TRUE);
  }
}
