<?php

use \Drupal\Core\Entity\Display\EntityFormDisplayInterface;

/**
 * Implements hook_entity_form_display_alter().
 *
 * Dynamically set the widget type for the field_json_metadata field.
 */
function data_dictionary_widget_entity_form_display_alter(EntityFormDisplayInterface $form_display, array $context) {
  if (_data_dictionary_data_type_checker($context) === 'data-dictionary') {
    $form_display->setComponent('field_json_metadata', [
      'type' => 'data_dictionary_widget',
    ]);
  }
}

/**
 * Find entity field_data_type or schema based on the context.
 *
 * @param array $context
 *   An associative array containing entity_type, bundle and form_mode.
 * 
 * @return string
 *   Schema/field_data_type value depending on form_mode.
 */
function _data_dictionary_data_type_checker($context) {
  if ($context['form_mode'] === "edit") {
    $node = \Drupal::routeMatch()->getParameter('node');
    if (\Drupal::routeMatch()->getParameter('node') instanceof \Drupal\node\NodeInterface && $node->hasField('field_data_type')) {
      return $node->get('field_data_type')->value;
    }
  }

  if ($context['form_mode'] === "default") {
    return \Drupal::request()->query->get('schema');
  }
}
