#!/bin/bash

if [ -d "./features" ]; then
    status_message "Your Behat directory is already configured." warning
    exit
fi

if [ ! -n "${url}" ]; then
    status_message "You need to specify the URL of a project using the \"--url=http://example.com\" parameter." error
fi

if [ ! -d "${package_dir}/behat" ]; then
    status_message "Something went wrong. Try to reinstall the package. :(" error
fi

cp -r ${package_dir}/behat/features ./
cp ${package_dir}/behat/behat.yml ./

project_dir=`pwd`/
project_exist=false

project_dir=${project_dir%/}
