<?php

/**
 * @file
 * Code for the DKAN Data Dictionary Mock module.
 */

use Dkan\DataDictionary\DataDictionaryInfo;

/**
 * Implements hook_xautoload().
 */
function dkan_data_dictionary_mock_xautoload($adapter) {
  $adapter->absolute()->addPsr4(
    'Dkan\DataDictionary\\',
    drupal_get_path("module", "dkan_data_dictionary_mock") . '/src'
  );
}

/**
 * Implements hook_dkan_data_dictionaries().
 */
function dkan_data_dictionary_mock_dkan_data_dictionaries() {
  $dataDictionaryInfo = new DataDictionaryInfo(
    'Dkan\DataDictionary\MockDataDictionaryManager',
    'mockdatadict',
    'Mock'
  );

  return array('mockdatadict' => $dataDictionaryInfo);
}
