<?php

/**
 * Implements hook_facetapi_widgets().
 */
function facet_icons_facetapi_widgets() {
  return array(
    'terms' => array(
      'handler' => array(
        'label' => t('Term Icon'),
        'class' => 'FacetapiTermIcon',
        'query types' => array('term', 'date'),
      ),
    ),
    'content_types' => array(
      'handler' => array(
        'label' => t('Content Type Icon'),
        'class' => 'FacetapiContentTypeIcon',
        'query types' => array('term', 'date'),
      ),
    ),
  );
}

/**
 * Theme function icons
 */
function theme_icon($variables) {
  $attributes = (isset($variables['attributes']))? $variables['attributes'] : array();
  $classes = (isset($variables['class']))? $variables['class'] : array();
  $classes[] = 'icon-dkan-' .  $variables['type'];
  $classes = implode(' ', $classes);
  return '<span class="icon-dkan ' . $classes . '" '. drupal_attributes($attributes) .'></span>';
}
