<?php

/**
 * @file
 * Install, update and uninstall functions for the metastore_search module.
 */

/**
 * Remove the legacy metastore_facets module.
 */
function dkan_metastore_facets_update_10001() {
  // Re-import default config for dkan_metastore_admin.
  \Drupal::service('config.installer')->installDefaultConfig('module', 'dkan_metastore_facets');

  // If the old metastore_admin module is still enabled, copy config and
  // uninstall it.
  if (\Drupal::moduleHandler()->moduleExists('metastore_facets')) {
    \Drupal::service('module_installer')->uninstall(['metastore_facets']);
    return t('The legacy metastore_facets module has been uninstalled.');
  }
}
