metastore.settings:
  type: config_object
  label: 'Metastore Settings'
  mapping:
    dictionary_mode:
      type: string
      label: 'Dictionary Mode'
    sitewide_dictionary_id:
      type: string
      label: 'Sitewide Dictionary ID'
    property_list:
      type: sequence
      label: 'Property List'
      sequence:
        type: string
        label: 'Property'