<?php
/**
 * @file
 * Custom elements for importing default pages.
 */

function dkan_default_pages_base_install(){
  ctools_include('pages', 'dkan_default_pages');
  // Save pages
  $pages = dkan_default_pages_available_pages();
  foreach($pages as $loadable){
    drupal_flush_all_caches();
    $page = call_user_func('dkan_default_pages_' . $loadable . '_page');
    $page = (object) $page;
    node_save($page);
  }
}