<?php

/**
 * @file
 * DKAN Fixtures Default module file.
 */

/**
 * Implements hook_migrate_api().
 */
function dkan_fixtures_default_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'dkan_fixtures_default_datasets' => array(
        'class_name' => 'DefaultContentDatasetImport',
        'group_name' => 'dkan_fixtures',
        'title' => t('DKAN Default Datasets'),
      ),
      'dkan_fixtures_default_resources' => array(
        'class_name' => 'DefaultContentResourceImport',
        'group_name' => 'dkan_fixtures',
        'title' => t('DKAN Default Resources'),
      ),
      'dkan_fixtures_default_groups' => array(
        'class_name' => 'DefaultContentGroupImport',
        'group_name' => 'dkan_fixtures',
        'title' => t('DKAN Default Groups'),
      ),
      'dkan_fixtures_default_visualization_entities' => array(
        'class_name' => 'DefaultContentVisualizationEntityImport',
        'group_name' => 'dkan_fixtures',
        'title' => t('DKAN Default Visualization Entities'),
      )
    ),
  );
  return $api;
}

/**
 * Implements hook_dkan_fixtures_register().
 */
function dkan_fixtures_default_dkan_fixtures_register() {
  return 'dkan_fixtures_default';
}


/**
 * Migration class used to import Default Datasets from fixtures.
 */
class DefaultContentDatasetImport extends MigrateCkanDatasetImport {

  /**
   * __construct().
   */
  public function __construct($arguments) {
    if (!isset($arguments['endpoint'])) {
      $arguments['endpoint'] = drupal_get_path('module', 'dkan_fixtures_default') . '/data/';
      $arguments['list_url'] = 'package_list.json';
      $arguments['item_url'] = 'package_show?id=:id.json';
    }

    // Add field mapping for topics.
    $this->addFieldMapping('field_topic', 'topic_names');

    parent::__construct($arguments);
  }

  /**
   * Prepares the row data for processing.
   */
  public function prepareRow($row) {
    parent::prepareRow($row);
    // Process topics.
    $topics = taxonomy_vocabulary_machine_name_load('dkan_topics');
    if (isset($row->dkan_additional_fields->field_topic)) {
      foreach ($row->dkan_additional_fields->field_topic as $topic) {
        $topic = $this->createTax($topic->value, 'dkan_topics', $topics->vid);
        $row->topic_names[] = $topic->name;
      }
    }
  }
}


/**
 * Migration class used to import Default Resources from fixtures.
 */
class DefaultContentResourceImport extends MigrateCkanResourceImport {

  /**
   * __construct().
   */
  public function __construct($arguments) {
    if (!isset($arguments['endpoint'])) {
      $arguments['endpoint'] = drupal_get_path('module', 'dkan_fixtures_default') . '/data/';
      $arguments['list_url'] = drupal_get_path('module', 'dkan_fixtures_default') . '/data/' . 'resource_list.json';
      $arguments['item_url'] = 'resource_show?id=:id.json';
    }
    parent::__construct($arguments);
  }

  /**
   * Do extra processing on the node data before its saved.
   */
  public function prepare($node, $row) {
    parent::prepare($node, $row);
    // Assign to 'Admin' user.
    $node->uid = 1;
    // Set up as published.
    $node->status = 1;
  }
}


/**
 * Migration class used to import Default Groups from fixtures.
 */
class DefaultContentGroupImport extends MigrateCkanGroupImport {

  /**
   * __construct().
   */
  public function __construct($arguments) {
    if (!isset($arguments['endpoint'])) {
      $arguments['endpoint'] = drupal_get_path('module', 'dkan_fixtures_default') . '/data/';
      $arguments['list_url'] = 'group_list.json';
      $arguments['item_url'] = 'group_show?id=:id.json';
    }
    parent::__construct($arguments);
  }
}

/**
 * Migration class used to import Default Visualization Entities from fixtures.
 */
class DefaultContentVisualizationEntityImport extends MigrateCkanBase {

  /**
   * __construct().
   */
  public function __construct($arguments) {
    if (!isset($arguments['endpoint'])) {
      $arguments['endpoint'] = drupal_get_path('module', 'dkan_fixtures_default') . '/data/';
      $arguments['list_url'] = 'visualization_entity_list.json';
      $arguments['item_url'] = 'visualization_entity_show?id=:id.json';
    }
    parent::__construct($arguments);
  }
}

/**
 * Deregisters migrations.
 */
function dkan_fixtures_default_migrations_disable() {
  Migration::deregisterMigration('dkan_fixtures_default_datasets');
  Migration::deregisterMigration('dkan_fixtures_default_resources');
  Migration::deregisterMigration('dkan_fixtures_default_groups');
  Migration::deregisterMigration('dkan_fixtures_default_visualization_entities');
}
