<?php

use Drupal\Core\Entity\EntityInterface;

use Drupal\dkan_common\Exception\DataNodeLifeCycleEntityValidationException;
use Drupal\dkan_metastore\NodeWrapper\Data;

/**
 * Determine whether the supplied entity is a dataset.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity in question.
 *
 * @return bool
 *   Whether the entity is a dataset.
 */
function _dkan_dkan_metastore_search_is_dataset(EntityInterface $entity): bool {
  try {
    // Attempt to check this entity's data type.
    return (new Data($entity, \Drupal::entityTypeManager()))->getDataType() === 'dataset';
  }
  catch (DataNodeLifeCycleEntityValidationException) {
    // If the data object fails validation, the given entity is not a dataset.
    return FALSE;
  }
}

/**
 * Implements hook_entity_insert().
 *
 * Track created datasets in the DKAN search api index.
 */
function dkan_metastore_search_entity_insert(EntityInterface $entity): void {
  // Ensure the entity in question is a dataset.
  // @todo Ensure it is not hidden or unpublished.
  if (!_dkan_metastore_search_is_dataset($entity)) {
    return;
  }

  $storage = \Drupal::service('entity_type.manager')->getStorage('search_api_index');
  $index = $storage->load('dkan');
  $index->trackItemsInserted('dkan_dataset', [$entity->uuid()]);
}

/**
 * Implements hook_entity_update().
 *
 * Track updated datasets in the DKAN search api index.
 */
function dkan_metastore_search_entity_update(EntityInterface $entity): void {
  // Ensure the entity in question is a dataset.
  if (!_dkan_metastore_search_is_dataset($entity)) {
    return;
  }

  $storage = \Drupal::service('entity_type.manager')->getStorage('search_api_index');
  $index = $storage->load('dkan');
  $index->trackItemsUpdated('dkan_dataset', [$entity->uuid()]);
}

/**
 * Implements hook_entity_delete().
 *
 * Track deleted datasets in the DKAN search api index.
 */
function dkan_metastore_search_entity_delete(EntityInterface $entity): void {
  // Ensure the entity in question is a dataset.
  if (!_dkan_metastore_search_is_dataset($entity)) {
    return;
  }

  $storage = \Drupal::service('entity_type.manager')->getStorage('search_api_index');
  $index = $storage->load('dkan');
  $index->trackItemsDeleted('dkan_dataset', [$entity->uuid()]);
}
