<?php
/**
 * @file
 * Code for the DKAN panels feature.
 */

include_once 'dkan_sitewide_panels.features.inc';

/**
 * Implements hook_preprocess_panels_style_collapsible().
 *
 * Ensures facets are expanded if in use.
 */
function dkan_sitewide_panels_preprocess_panels_style_collapsible(&$variables) {

  // Get the active searchers. For example search_api@datasets
  foreach (facetapi_get_active_searchers() as $searcher) {

    // Load the facet adapter to load all the facets later.
    $adapter = facetapi_adapter_load($searcher);

    // Find out if the pane matches a facet in the query string; un-collapse if so
    $pane = $variables['pane'];
    if (substr($pane->type, 0, 8)) {
      foreach (array_keys($adapter->getAllActiveItems()) as $param) {
        // We match the first part of the param to a mapped facet name
        $param_parts = explode(':', $param, 2);
        $param_name = $param_parts[0];
        // The pane subtype will be something like "facetapi-wsVI1ENUXwf4Rz08n9fg2WvfQ0Gs5h2a"
        $facet_hash = substr($pane->subtype, 9);
        $facet_delta_map = facetapi_get_delta_map();
        if (in_array($facet_hash, array_keys($facet_delta_map))) {
          $mapping_parts = explode(':', $facet_delta_map[$facet_hash]);
          $facet_name = $mapping_parts[2];
          if ($facet_name == $param_name) {
            $variables['collapsed'] = 0;
          }
        }
      }
    }
  }
}
