<?php

/**
 * @file
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\dkan_datastore\DataNodeLifeCycle;
use Drupal\dkan_common\Exception\DataNodeLifeCycleEntityValidationException;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function dkan_datastore_node_insert(EntityInterface $entity) {
  try {
    (new DataNodeLifeCycle($entity))->insert();
  }
  catch (DataNodeLifeCycleEntityValidationException $e) {
  }
}
