<?php

use Drupal\dkan_common\Tests\Mock\Options;
use Drupal\Component\DependencyInjection\Container;
use Drupal\dkan_common\Tests\Mock\Chain;
use Procrastinator\Result;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RequestStack;
use Contracts\Mock\Storage\MemoryFactory;
use Drupal\dkan_harvest\Harvester;
use Drupal\dkan_common\Tests\DkanTestBase;
use Drupal\dkan_harvest\Controller\Api;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 *
 */
class ApiTest extends DkanTestBase {

  private $request;

  /**
   *
   */
  public function getContainer() {
    // TODO: Change the autogenerated stub.
    parent::setUp();

    $container = $this->getMockBuilder(ContainerInterface::class)
      ->setMethods(['get'])
      ->disableOriginalConstructor()
      ->getMockForAbstractClass();

    $container->method('get')
      ->with(
        $this->logicalOr(
          $this->equalTo('dkan_harvest.service'),
          $this->equalTo('dkan_harvest.logger_channel'),
          $this->equalTo('request_stack')
        )
      )
      ->will($this->returnCallback([$this, 'containerGet']));

    return $container;
  }

  /**
   *
   */
  public function containerGet($input) {
    switch ($input) {
      case 'dkan_harvest.service':
        return new Harvester(new MemoryFactory());

      break;
      case 'request_stack':
        $stack = $this->getMockBuilder(RequestStack::class)
          ->disableOriginalConstructor()
          ->setMethods(['getCurrentRequest'])
          ->getMock();

        $stack->method("getCurrentRequest")->willReturn($this->request);

        return $stack;

      break;
    }
  }

  /**
   *
   */
  public function testEmptyIndex() {
    $controller = new Api($this->getContainer());
    $response = $controller->index();
    $this->assertEquals(JsonResponse::class, get_class($response));
    $this->assertEquals($response->getContent(), json_encode([]));
  }

  /**
   *
   */
  public function testBadPlan() {
    $this->request = new Request();
    $controller = new Api($this->getContainer());
    $response = $controller->register();
    $this->assertEquals(JsonResponse::class, get_class($response));
    $this->assertEquals($response->getContent(), json_encode(["message" => "Harvest plan must be a php object."]));
  }

  /**
   *
   */
  public function testRegisterAndIndex() {
    $request = $this->getMockBuilder(Request::class)
      ->setMethods(['getContent'])
      ->disableOriginalConstructor()
      ->getMock();

    $plan = [
      'identifier' => 'test',
      'extract' => ['type' => "blah", "uri" => "http://blah"],
      'load' => ['type' => 'blah'],
    ];

    $request->method('getContent')->willReturn(json_encode($plan));

    $this->request = $request;

    $controller = new Api($this->getContainer());
    $response = $controller->register();
    $this->assertEquals(JsonResponse::class, get_class($response));
    $this->assertEquals($response->getContent(), json_encode(["identifier" => "test"]));

    $response = $controller->index();
    $this->assertEquals(JsonResponse::class, get_class($response));
    $this->assertEquals($response->getContent(), json_encode(["test"]));
  }

  /**
   *
   */
  public function testRun() {
    $options = (new Options())
      ->add("request_stack", RequestStack::class)
      ->add("dkan_harvest.service", Harvester::class);

    $container = (new Chain($this))
      ->add(Container::class, "get", $options)
      ->add(RequestStack::class, 'getCurrentRequest', Request::class)
      ->add(Request::class, 'getContent', json_encode((object) ['plan_id' => 'test']))
      ->add(Harvester::class, "runHarvest", Result::class)
      ->getMock();

    $controller = Api::create($container);
    $response = $controller->run();
    $this->assertEquals(JsonResponse::class, get_class($response));
  }

}
