#!/bin/bash

# TODO: Determine all the places to look for testUsers.json/yml.

## Description: Add users to the site for QA.
## Usage: dkan-test-users [path] [--remove]

# Path is optional. If the first arg has double hyphens, it's the flag.
TESTUSER_PATH="testUsers.json"
if [[ ! ${1} = --* ]] ; then
  TESTUSER_PATH=${1}
  shift
fi

# Flag arguments.
TESTUSER_REMOVE=false
while :; do
  case ${1:-} in
  --remove)
    TESTUSER_REMOVE=true
    shift
    ;;
  --) # End of all options.
    shift
    break
    ;;
  -?*)
    printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
    ;;
  *) # Default case: No more options, so break out of the loop.
    break ;;
  esac
  shift
done

if [ ! -f $TESTUSER_PATH ]; then
  echo "$TESTUSER_PATH not found."
  exit 1
fi

if [ $TESTUSER_REMOVE = true ]; then
  echo "Removing users from $TESTUSER_PATH"
else
  echo "Adding users from $TESTUSER_PATH"
fi

# yq/jq magical incantations.
readarray -t TESTUSER_TEST_USERS < <(yq -c '.[]' $TESTUSER_PATH)
for TESTUSER_TESTUSER in "${TESTUSER_TEST_USERS[@]}"; do
  name=$(yq -r '.name' <<<"$TESTUSER_TESTUSER")
  mail=$(yq -r '.mail' <<<"$TESTUSER_TESTUSER")
  role=$(yq -r '.role' <<<"$TESTUSER_TESTUSER")
  if [ $TESTUSER_REMOVE = true ]; then
    drush user:cancel --delete-content $name -y
  else
    drush user:create $name --password=$name --mail=$mail
    drush user-add-role $role $name
  fi
done
