#!/bin/bash

## Description: Add users to the site for QA.
## Usage: dkan-test-users [path] [--remove]

# Get the path, which is optional. If the first arg has double hyphens, it's
# the flag.
if [[ ${1} != --* ]] ; then
  TU_PATH=${1}
  shift
fi

# Glean flag arguments.
TU_REMOVE=false
while :; do
  case ${1:-} in
  --remove)
    TU_REMOVE=true
    shift
    ;;
  --) # End of all options.
    shift
    break
    ;;
  -?*)
    printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
    ;;
  *) # Default case: No more options, so break out of the loop.
    break ;;
  esac
  shift
done

# If we didn't get an argument, use the default.
if [ -z $TU_PATH ] ; then
  TU_PATH="testUsers.json"
fi

if [ ! -f $TU_PATH ] ; then
  echo "$TU_PATH not found."
  exit 1
fi

if [ $TU_REMOVE = true ]; then
  echo "Removing users from $TU_PATH"
else
  echo "Adding users from $TU_PATH"
fi

# yq/jq magical incantations.
readarray -t TU_TEST_USERS < <(yq -c '.[]' $TU_PATH)
for TU_TEST_USER in "${TU_TEST_USERS[@]}"; do
  name=$(yq -r '.name' <<<"$TU_TEST_USER")
  mail=$(yq -r '.mail' <<<"$TU_TEST_USER")
  role=$(yq -r '.role' <<<"$TU_TEST_USER")
  if [ $TU_REMOVE = true ]; then
    drush user:cancel --delete-content $name -y
  else
    drush user:create $name --password=$name --mail=$mail
    drush user-add-role $role $name
  fi
done
