<?php

/**
 * @file
 * dkan_topics.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function dkan_topics_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_icon_type'.
  $field_bases['field_icon_type'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_icon_type',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'font' => 'Font Icon',
        'image' => 'Image',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_topic'.
  $field_bases['field_topic'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_topic',
    'indexes' => array(
      'tid' => array(
        0 => 'tid',
      ),
    ),
    'locked' => 0,
    'module' => 'taxonomy',
    'settings' => array(
      'allowed_values' => array(
        0 => array(
          'vocabulary' => 'dkan_topics',
          'parent' => 0,
        ),
      ),
    ),
    'translatable' => 0,
    'type' => 'taxonomy_term_reference',
  );

  // Exported field_base: 'field_topic_icon'.
  $field_bases['field_topic_icon'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_topic_icon',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'font_icon_select',
    'settings' => array(
      'font' => 1,
      'font_blacklist' => '',
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'font_icon_select_icon',
  );

  // Exported field_base: 'field_topic_icon_color'.
  $field_bases['field_topic_icon_color'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_topic_icon_color',
    'indexes' => array(
      'rgb' => array(
        0 => 'rgb',
      ),
    ),
    'locked' => 0,
    'module' => 'color_field',
    'settings' => array(
      'allow_empty' => 1,
      'palette' => '',
      'show_buttons' => 1,
      'show_input' => 1,
      'show_palette' => 0,
      'show_palette_only' => 0,
    ),
    'translatable' => 0,
    'type' => 'color_field_rgb',
  );

  return $field_bases;
}
